runmod = gather_ws
<server gather.crazierl.net>
	port = 80
	listen = 162.248.4.51
	appmods = </, gather_ws>
</server>

<server gather.crazierl.net>
	port = 443
	listen = 162.248.4.51
	appmods = </, gather_ws>
	<ssl>
		protocol_version = tlsv1.3
		keyfile = /var/db/yaws/.acme.sh/gather.crazierl.net_ecc/gather.crazierl.net.key
		certfile = /var/db/yaws/.acme.sh/gather.crazierl.net_ecc/fullchain.cer
	</ssl>
</server>

